### ISSUE TITLE
Cannot install Loaf

### ISSUE THREAD

**Issue by pepejeria** [schmidyy/Loaf#28]
I followed the instructions and added Load to my Podfile:

`pod 'Loaf'`

then ran `pod install`, which resulted in the following error:
```
[!] CocoaPods could not find compatible versions for pod "Loaf":
  In Podfile:
    Loaf

Specs satisfying the `Loaf` dependency were found, but they required a higher minimum deployment target.
```

Cocoapods version 1.9.1
Project target is set to 10.3

**Comment by ludivinefafournoux** [comment]
I have the same problem

**Comment by rajdhakate** [comment]
+1. exactly the same problem. 
Minimum deployment target is set to 10.0. Docs says Loaf require iOS 9.0+

**Comment by kongtianxintang** [comment]
I have the same problem
code:
`platform:ios,'10.0'
target 'XXX' do 
  #toast
  pod 'Loaf'
end
`

**Comment by link60** [comment]
Hello
Same problem here :/ 

[Edit] Ended up by adding the dependency with Swift Package, all works fine now :)

**Comment by romaHerman** [comment]
The problem is that in pod spec iOS version is specified as 9.0 but swift version is set to 5.2 which is available since iOS 11. 
@schmidyy could you please specify min swift version as 4.2 then everything works normally. I just tested by downloading code modifying pod spec and installing pod as local developer pod.
